const languages = {
	en: {
		//MAIN PAGE
		mainTitle: "Periodic Table of Elements",
		lanthanides: "Lanthanides",
		actinides: "Actinides",
		legend: "Legend",
		legendAlkaliMetals: "Alkali metals",
		legendAlkalineEarthMetals: "Alkaline E. Metals",
		legendTransitionMetals: "Transition metals",
		legendLanthanides: "Lanthanides",
		legendActinides: "Actinides",
		legendOtherMetals: "Other metals",
		legendMetalloids: "Metalloids",
		legendNonmetals: "Nonmetals",
		legendHalogens: "Halogens",
		legendNobleGases: "Noble gases",
		searchPlaceholder: "Enter an element's name...",
	},
	mk: {
		//MAIN PAGE
		mainTitle: "Периодна табела на елементите",
		lanthanides: "Лантаниди",
		actinides: "Актиниди",
		legend: "Легенда",
		legendAlkaliMetals: "Алкални метали",
		legendAlkalineEarthMetals: "Алкални З. метали",
		legendTransitionMetals: "Транз. метали",
		legendLanthanides: "Лантаниди",
		legendActinides: "Актиниди",
		legendOtherMetals: "Други метали",
		legendMetalloids: "Металоиди",
		legendNonmetals: "Неметали",
		legendHalogens: "Халогени",
		legendNobleGases: "Благородни гасови",
		searchPlaceholder: "Внесете име на елементот...",
	},
};
