const languages = {
	en: {
		//MAIN PAGE
		mainTitle: "Periodic Table of Elements",
		lanthanides: "Lanthanides",
		actinides: "Actinides",
		legend: "Legend",
		legendAlkaliMetals: "Alkali metals",
		legendAlkalineEarthMetals: "Alkaline E. Metals",
		legendTransitionMetals: "Transition metals",
		legendLanthanides: "Lanthanides",
		legendActinides: "Actinides",
		legendOtherMetals: "Other metals",
		legendMetalloids: "Metalloids",
		legendNonmetals: "Nonmetals",
		legendHalogens: "Halogens",
		legendNobleGases: "Noble gases",
		searchPlaceholder: "Enter an element's name...",
		//ELEMENT DETAILS PAGE
		//1.left-side-ul-props
		modalElementInfoAtomWeight: "Atomic Weight",
		modalElementInfoDensity: "Density",
		modalElementInfoMeltingPoint: "Melting Point",
		modalElementInfoBoilingPoint: "Boiling Point",
		//2.right-side-ul-props
		//2.1 Overview
		modalCategoryOverviewTitle: "01.Overview",
		modalCategoryOverviewSymbol: "Symbol",
		modalCategoryOverviewAtomNumber: "Atomic Number",
		modalCategoryOverviewAtomWeight: "Atomic Weight",
		modalCategoryOverviewDensity: "Density",
		modalCategoryOverviewMeltingPoint: "Melting point",
		modalCategoryOverviewBoilingPoint: "Boling point",
		//2.2 Thermal properties
		modalCategoryThermalTitle: "02.Thermal Properties",
		modalCategoryThermalPhase: "Phase",
		modalCategoryThermalMeltingPoint: "Melting point",
		modalCategoryThermalBoilingPoint: "Boiling point",
		modalCategoryThermalAbsMeltingPoint: "Absolute melting point",
		modalCategoryThermalAbsBoilingPoint: "Absolute boiling point",
		modalCategoryThermalCritPressure: "Critical pressure",
		modalCategoryThermalCritTemp: "Critical temperature",
		modalCategoryThermalFusionHeat: "Heat of fusion",
		modalCategoryThermalVapourHeat: "Heat of vaporization",
		modalCategoryThermalCombHeat: "Heat of combustion",
		modalCategoryThermalSpecHeat: "Specific heat",
		modalCategoryThermalAdiabIdx: "Adiabatic index",
		modalCategoryThermalNeelPoint: "Neel point",
		modalCategoryThermalThermalConduct: "Thermal conductivity",
		modalCategoryThermalThermalExpansion: "Thermal expansion",
		//2.3 Physical properties
		modalCategoryPhysicalTitle: "03.Physical Properties",
		modalCategoryPhysicalDensity: "Density",
		modalCategoryPhysicalDensityLiq: "Density(liquid)",
		modalCategoryPhysicalMolarVolume: "Molar volume",
		modalCategoryPhysicalBrinell: "Brinell hardness",
		modalCategoryPhysicalMohs: "Mohs hardness",
		modalCategoryPhysicalShear: "Shear modulus",
		modalCategoryPhysicalBulk: "Bulk modulus",
		modalCategoryPhysicalMolarHeat: "Molar heat",
		modalCategoryPhysicalThermalExpansion: "Thermal expansion",
		//2.4 Reactivity
		modalCategoryReactivityTitle: "04.Reactivity",
		modalCategoryReactivityValence: "Valence",
		modalCategoryReactivityElNegativity: "Electronegativity",
		modalCategoryReactivityElectronAffinity: "Electron affinity",
		modalCategoryReactivityIonizationEnergy: "Ionization energy",
		//2.5 Safety
		modalCategorySafetyTitle: "05.Safety",
		modalCategorySafetyAutoignitionPoint: "Autoignition point",
		modalCategorySafetyFlashPoint: "Flash point",
		modalCategorySafetyCombustionHeat: "Combustion heat",
		//2.6 Classifications
		modalCategoryClassificationsTitle: "06.Classifications",
		modalCategoryClassificationsAltNames: "Alternative names",
		modalCategoryClassificationsAlotropNames: "Allotrops names",
		modalCategoryClassificationsBlock: "Block",
		modalCategoryClassificationsGroup: "Group",
		modalCategoryClassificationsPeriod: "Period",
		modalCategoryClassificationsColor: "Color",
		modalCategoryClassificationsDiscover: "Discovered",
		modalCategoryClassificationsGasPhase: "Gas phase",
		//2.7 Electrical properties
		modalCategoryElecpropsTitle: "07.Electrical properties",
		modalCategoryElecpropsElecType: "Electrical type",
		modalCategoryElecpropsElecConduct: "Electrical conductivity",
		modalCategoryElecpropsResist: "ResistivityN",
		modalCategoryElecpropsSuperPoint: "Superconductivity point",
		//2.8 Magnetic properties
		modalCategoryMagnPropsTitle: "08.Magnetic properties",
		modalCategoryMagnPropsType: "Magnetic type",
		modalCategoryMagnPropsCuriePoint: "Curie point",
		modalCategoryMagnPropsMassSusceptibility: "Mass susceptibility",
		modalCategoryMagnPropsVolumeSusceptibility: "Volume susceptibility",
		//2.9 Abundance
		modalCategoryAbudanceTitle: "09.Abundance",
		modalCategoryAbudanceUniverse: "In the universe",
		modalCategoryAbudanceSun: "In the sun",
		modalCategoryAbudanceMeteorites: "In meteorites",
		modalCategoryAbudanceCrust: "In the earth's crust",
		modalCategoryAbudanceOceans: "In oceans",
		modalCategoryAbudanceHumans: "In humans",
		//2.10 Atomic dimensions and structures
		modalCategoryAtomStructureTitle: "10.Atom dimensions and structures",
		modalCategoryAtomStructureRadius: "Atomic radius",
		modalCategoryAtomStructureCovalent: "Covalent radius",
		modalCategoryAtomStructureVanderWaals: "Van der Waals radius",
		modalCategoryAtomStructureCrystalStruc: "Crystal structure",
		modalCategoryAtomStructureLatticeAngles: "Lattice angles",
		modalCategoryAtomStructureLatticeConst: "Lattice constants",
		modalCategoryAtomStructureSpaceGroupName: "Space group name",
		modalCategoryAtomStructureSpaceGroupNumber: "Space group number",
		//2.11 Nuclear properties
		modalCategoryNuclearTitle: "11.Nuclear properties",
		modalCategoryNuclearHalfLife: "Halflife",
		modalCategoryNuclearLifetime: "Lifetime",
		modalCategoryNuclearDecay: "Decay mode",
		modalCategoryNuclearQuantumNum: "Quantum numbers",
		modalCategoryNuclearNeutronCross: "Neutron cross section",
		modalCategoryNuclearNeutMassAbs: "N.mass absorption",
		modalCategoryNuclearKnownIsot: "Known isotopes",
		modalCategoryNuclearStableIsot: "Stable isotopes",
		modalCategoryNuclearIsotAbundance: "Isotopes abundance",
	},
	mk: {
		//MAIN PAGE
		mainTitle: "Периодна табела на елементите",
		lanthanides: "Лантаниди",
		actinides: "Актиниди",
		legend: "Легенда",
		legendAlkaliMetals: "Алкални метали",
		legendAlkalineEarthMetals: "Земноалк. метали",
		legendTransitionMetals: "Транз. метали",
		legendLanthanides: "Лантаниди",
		legendActinides: "Актиниди",
		legendOtherMetals: "Други метали",
		legendMetalloids: "Металоиди",
		legendNonmetals: "Неметали",
		legendHalogens: "Халогени",
		legendNobleGases: "Благородни гасови",
		searchPlaceholder: "Внесете име на елементот...",
		//ELEMENT DETAILS PAGE
		//left-side-ul-props
		modalElementInfoAtomWeight: "Атомска тежина",
		modalElementInfoDensity: "Густина",
		modalElementInfoMeltingPoint: "Точка на топење",
		modalElementInfoBoilingPoint: "Точка на вриење",
		//2.right-side-ul-props
		//2.1 Overview
		modalCategoryOverviewTitle: "01.Преглед",
		modalCategoryOverviewSymbol: "Симбол",
		modalCategoryOverviewAtomNumber: "Атомски број",
		modalCategoryOverviewAtomWeight: "Атомска тежина",
		modalCategoryOverviewDensity: "Густина",
		modalCategoryOverviewMeltingPoint: "Точка на топење",
		modalCategoryOverviewBoilingPoint: "Точка на вриење",
		//2.2 Thermal properties
		modalCategoryThermalTitle: "02.Топлински својства",
		modalCategoryThermalPhase: "Фаза",
		modalCategoryThermalMeltingPoint: "Точка на топење",
		modalCategoryThermalBoilingPoint: "Точка на вриење",
		modalCategoryThermalAbsMeltingPoint: "Апсолутна точка на топење",
		modalCategoryThermalAbsBoilingPoint: "Апсолутна точка на вриење",
		modalCategoryThermalCritPressure: "Критичен притисок",
		modalCategoryThermalCritTemp: "Критична температура",
		modalCategoryThermalFusionHeat: "Топлина на фузија",
		modalCategoryThermalVapourHeat: "Топлина на испарување",
		modalCategoryThermalCombHeat: "Топлина на согорување",
		modalCategoryThermalSpecHeat: "Специфична топлина",
		modalCategoryThermalAdiabIdx: "Адиабатски индекс",
		modalCategoryThermalNeelPoint: "Нил точка",
		modalCategoryThermalThermalConduct: "Термичка спроводливост",
		modalCategoryThermalThermalExpansion: "Термичка експанзија",
		//2.3 Physical properties
		modalCategoryPhysicalTitle: "03.Физички својства",
		modalCategoryPhysicalDensity: "Густина",
		modalCategoryPhysicalDensityLiq: "Густина(течност)",
		modalCategoryPhysicalMolarVolume: "Моларен волумен",
		modalCategoryPhysicalBrinell: "Бринелова тврдина",
		modalCategoryPhysicalMohs: "Мосова тврдина",
		modalCategoryPhysicalShear: "Shear модулус",
		modalCategoryPhysicalBulk: "Bulk модулус",
		modalCategoryPhysicalMolarHeat: "Моларна топлина",
		modalCategoryPhysicalThermalExpansion: "Термичка експанзија",
		//2.4 Reactivity
		modalCategoryReactivityTitle: "04.Реактивност",
		modalCategoryReactivityValence: "Валентност",
		modalCategoryReactivityElNegativity: "Електронегативност",
		modalCategoryReactivityElectronAffinity: "Електронски афинитет",
		modalCategoryReactivityIonizationEnergy: "Енергија на јонизација",
		//2.5 Safety
		modalCategorySafetyTitle: "05.Безбедност",
		modalCategorySafetyAutoignitionPoint: "Точка на самозапалување",
		modalCategorySafetyFlashPoint: "Флеш точка",
		modalCategorySafetyCombustionHeat: "Точка на согорување",
		//2.6 Classifications
		modalCategoryClassificationsTitle: "06.Класификации",
		modalCategoryClassificationsAltNames: "Алтернативни имиња",
		modalCategoryClassificationsAlotropNames: "Имиња на алотропи",
		modalCategoryClassificationsBlock: "Блок",
		modalCategoryClassificationsGroup: "Група",
		modalCategoryClassificationsPeriod: "Периода",
		modalCategoryClassificationsColor: "Боја",
		modalCategoryClassificationsDiscover: "Пронајдено",
		modalCategoryClassificationsGasPhase: "Гасна фаза",
		//2.7 Electrical properties
		modalCategoryElecpropsTitle: "07.Електрични својства",
		modalCategoryElecpropsElecType: "Електронски тип",
		modalCategoryElecpropsElecConduct: "Електронскa спроводливост",
		modalCategoryElecpropsResist: "Отпорност",
		modalCategoryElecpropsSuperPoint: "Точка суперспроводливост",
		//2.8 Magnetic properties
		modalCategoryMagnPropsTitle: "08.Магнетни својства",
		modalCategoryMagnPropsType: "Магнетен тип",
		modalCategoryMagnPropsCuriePoint: "Curie точка",
		modalCategoryMagnPropsMassSusceptibility: "Тежинска осетливост",
		modalCategoryMagnPropsVolumeSusceptibility: "Волуменска осетливост",
		//2.9 Abundance
		modalCategoryAbudanceTitle: "09.Застапеност",
		modalCategoryAbudanceUniverse: "Во универзумот",
		modalCategoryAbudanceSun: "Во сонцето",
		modalCategoryAbudanceMeteorites: "Во метеорити",
		modalCategoryAbudanceCrust: "Во земјина кора",
		modalCategoryAbudanceOceans: "Во океаните",
		modalCategoryAbudanceHumans: "Во човекот",
		//2.10 Atomic dimensions and structures
		modalCategoryAtomStructureTitle: "10.Димензии и структури на атом",
		modalCategoryAtomStructureRadius: "Атомски радиус",
		modalCategoryAtomStructureCovalent: "Ковалентен радиус",
		modalCategoryAtomStructureVanderWaals: "Van der Waals радиус",
		modalCategoryAtomStructureCrystalStruc: "Кристална структура",
		modalCategoryAtomStructureLatticeAngles: "Решеткасти агли",
		modalCategoryAtomStructureLatticeConst: "Решеткасти константи",
		modalCategoryAtomStructureSpaceGroupName: "Име на просторна група",
		modalCategoryAtomStructureSpaceGroupNumber: "Број на просторна група",
		//2.11 Nuclear properties
		modalCategoryNuclearTitle: "11.Нуклеарни својства",
		modalCategoryNuclearHalfLife: "Полуживот",
		modalCategoryNuclearLifetime: "Животен век",
		modalCategoryNuclearDecay: "Режим на распаѓање",
		modalCategoryNuclearQuantumNum: "Квантни броеви",
		modalCategoryNuclearNeutronCross: "Пресек на неутрон",
		modalCategoryNuclearNeutMassAbs: "Абсорпција на маса",
		modalCategoryNuclearKnownIsot: "Познати изотопи",
		modalCategoryNuclearStableIsot: "Стабилни изотопи",
		modalCategoryNuclearIsotAbundance: "Достапност на изотопи",
	},
};
